import React, { useState, useCallback } from 'react';
import {
  ReactFlow,
  ReactFlowProvider,
  Background,
  BackgroundVariant,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { v4 as uuidv4 } from 'uuid';
import CustomNode from './CustomNode';
import AddStepNode from './AddStepNode';
import RightDrawer from './RightDrawer';
import CustomEdge from './CustomEdge';
import { Loader2 } from 'lucide-react';
import { useDrawer } from '../contexts/DrawerContext';
import { useFlowLogic } from '../hooks/useFlowLogic';
import { useTemplates } from '../hooks/useTemplates';
import { useKeyboardShortcuts } from '../hooks/useKeyboardShortcuts';
import { FlowControls } from './Flow/FlowControls';
import { FlowModals } from './Flow/FlowModals';
import { CustomMiniMap } from './Flow/CustomMiniMap';
import { generateWorkflowFromPrompt } from '../services/aiWorkflowService';
import { Sparkles, Calendar, MapPin, Phone, CreditCard, User } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from './ui/dialog';
import { Button } from './ui/button';
import { Textarea } from './ui/textarea';
import { showSuccessToast, showErrorToast } from '../utils/toast';
import { crmService } from '../services/crmService';
import { Agreement, FinancialSummary } from '../types/crm';
import { format, parseISO } from 'date-fns';
import { tr } from 'date-fns/locale';
import { useEffect } from 'react';

const nodeTypes = {
  workstation: CustomNode,
  addStep: AddStepNode,
};

const edgeTypes = {
  default: CustomEdge,
};

interface FlowProps {
  workflowId: string;
  initialMode?: 'ai' | 'manual' | null;
  onBack: () => void;
  onOpenSettings?: () => void;
}

function Flow({ workflowId, initialMode, onBack, onOpenSettings }: FlowProps) {
  const {
    nodes, setNodes, onNodesChange,
    edges, setEdges, onEdgesChange,
    isLoading, isSaving, workflowName, setWorkflowName,
    hasUnsavedChanges, agreementId,
    onConnect, onSave, onLayout, onDuplicate, onDrop
  } = useFlowLogic(workflowId);

  const { openDrawer, isOpen, closeDrawer } = useDrawer();
  const [showClearConfirm, setShowClearConfirm] = useState(false);
  const [showMiniMap, setShowMiniMap] = useState(true);
  const [showAgreementInfo, setShowAgreementInfo] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const [agreement, setAgreement] = useState<Agreement | null>(null);
  const [financialSummary, setFinancialSummary] = useState<FinancialSummary | null>(null);

  useEffect(() => {
    if (agreementId) {
      crmService.getAgreement(agreementId).then(setAgreement).catch(console.error);
      crmService.getFinancialSummary(agreementId).then(setFinancialSummary).catch(console.error);
    }
  }, [agreementId]);

  const {
    showTemplateModal,
    setShowTemplateModal,
    templateName,
    setTemplateName,
    handleSaveTemplate
  } = useTemplates(nodes, edges);

  useKeyboardShortcuts(onDuplicate);

  const confirmClear = useCallback(() => {
    setNodes([{
      id: uuidv4(),
      type: 'addStep',
      position: { x: 0, y: 0 },
      data: {}
    }]);
    setEdges([]);
    setShowClearConfirm(false);
  }, [setNodes, setEdges]);

  const onDragOver = useCallback((event: React.DragEvent) => {
    event.preventDefault();
    event.dataTransfer.dropEffect = 'move';
  }, []);

  const handleAddNewNode = () => {
    const addStepNode = nodes.find(n => n.type === 'addStep');
    if (addStepNode) {
      openDrawer('addNode', addStepNode.id);
    } else if (nodes.length > 0) {
      const rightmostNode = nodes.reduce((prev, current) => {
        return (prev.position.x > current.position.x) ? prev : current;
      });
      openDrawer('addNode', rightmostNode.id);
    } else {
      const id = uuidv4();
      setNodes(nds => [...nds, {
        id,
        type: 'addStep',
        position: { x: 0, y: 0 },
        data: {}
      }]);
      openDrawer('addNode', id);
    }
  };

  const handleGenerateAiWorkflow = async (currentAgreement: Agreement | null = agreement) => {
    setIsGenerating(true);
    try {
      const defaultPrompt = currentAgreement 
        ? `${currentAgreement.eventCategoryName} için standart bir iş akışı oluştur.` 
        : "Standart bir iş akışı oluştur.";
        
      const result = await generateWorkflowFromPrompt(defaultPrompt, currentAgreement);
      
      if (result && result.nodes && result.edges) {
        // Map the generated nodes to our internal format
        const newNodes = result.nodes.map((n: any) => ({
          id: n.id,
          type: 'workstation',
          position: n.position,
          data: {
            title: n.data.label,
            type: n.data.type,
            date: n.data.date,
            assignee: n.data.assignee,
            status: n.data.status,
            assets: n.data.assets || [],
            onEdit: () => openDrawer(n.id)
          }
        }));
        
        // Map the generated edges to our internal format
        const newEdges = result.edges.map((e: any) => ({
          id: e.id,
          source: e.source,
          target: e.target,
          type: 'default',
          animated: true,
          style: { stroke: '#94a3b8', strokeWidth: 2 }
        }));
        
        setNodes(newNodes);
        setEdges(newEdges);
        
        // Mark workflow as AI generated
        await fetch(`/api/workflows/${workflowId}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ is_ai_generated: true })
        });
        
        showSuccessToast('İş akışı başarıyla oluşturuldu');
      }
    } catch (error: any) {
      console.error(error);
      const errorMessage = error?.message || 'İş akışı oluşturulurken bir hata oluştu';
      showErrorToast(errorMessage);
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (initialMode === 'ai' && agreement && !hasAutoGenerated && nodes.length <= 1) {
      setHasAutoGenerated(true);
      handleGenerateAiWorkflow(agreement);
    }
  }, [initialMode, agreement, hasAutoGenerated, nodes.length]);

  if (isLoading || isGenerating) {
    return (
      <div className="flex-grow h-full flex items-center justify-center bg-gray-50 dark:bg-slate-800">
        <Loader2 className="w-8 h-8 text-primary animate-spin" />
      </div>
    );
  }

  return (
    <div className="flex-grow h-full relative">
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        onDrop={onDrop}
        onDragOver={onDragOver}
        nodeTypes={nodeTypes}
        edgeTypes={edgeTypes}
        fitView
        fitViewOptions={{ maxZoom: 1, minZoom: 0.1 }}
        defaultViewport={{ x: 0, y: 0, zoom: 1 }}
        className="bg-gray-100 dark:bg-slate-800"
      >
        <Background 
          variant={BackgroundVariant.Dots} 
          gap={24} 
          size={1.5} 
          color="#9ca3af" 
          bgColor="transparent"
        />
        
        <CustomMiniMap showMiniMap={showMiniMap} />

        <FlowControls 
          onBack={onBack}
          workflowName={workflowName}
          onWorkflowNameChange={setWorkflowName}
          isSaving={isSaving}
          hasUnsavedChanges={hasUnsavedChanges}
          showMiniMap={showMiniMap}
          onToggleMiniMap={() => setShowMiniMap(!showMiniMap)}
          showAgreementInfo={showAgreementInfo}
          onToggleAgreementInfo={() => setShowAgreementInfo(!showAgreementInfo)}
          onLayout={onLayout}
          onDuplicate={onDuplicate}
          onClear={() => setShowClearConfirm(true)}
          onSave={() => onSave()}
          onShowTemplateModal={() => setShowTemplateModal(true)}
          isDrawerOpen={isOpen}
          onToggleDrawer={() => isOpen ? closeDrawer() : openDrawer('addNode', nodes[0]?.id || '')}
          onAddNewNode={handleAddNewNode}
          onOpenSettings={onOpenSettings}
        />
        
        {agreement && showAgreementInfo && (
          <div className="absolute top-20 left-6 z-50 bg-white/90 dark:bg-slate-800/90 backdrop-blur-md p-4 rounded-xl shadow-lg border border-gray-200 dark:border-slate-700 w-80">
            <h3 className="font-semibold text-gray-900 dark:text-white mb-3 border-b border-gray-100 dark:border-slate-700 pb-2 flex items-center gap-2">
              <User className="w-4 h-4 text-primary" />
              {agreement.accountName}
            </h3>
            
            <div className="space-y-2 text-sm">
              <div className="flex items-start gap-2 text-gray-600 dark:text-slate-300">
                <Calendar className="w-4 h-4 mt-0.5 shrink-0 text-gray-400" />
                <div>
                  <p>{format(parseISO(agreement.eventStartDate), 'd MMM yyyy HH:mm', { locale: tr })}</p>
                  <p className="text-xs text-gray-500">{agreement.eventCategoryName}</p>
                </div>
              </div>
              
              <div className="flex items-center gap-2 text-gray-600 dark:text-slate-300">
                <MapPin className="w-4 h-4 shrink-0 text-gray-400" />
                <span className="truncate">{agreement.venueName} - {agreement.hallName}</span>
              </div>
              
              <div className="flex items-center gap-2 text-gray-600 dark:text-slate-300">
                <Phone className="w-4 h-4 shrink-0 text-gray-400" />
                <span>{agreement.customerPhone}</span>
              </div>
              
              {financialSummary && (
                <div className="mt-3 pt-3 border-t border-gray-100 dark:border-slate-700">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs text-gray-500 flex items-center gap-1">
                      <CreditCard className="w-3 h-3" /> Finansal Durum
                    </span>
                    <span className="text-xs font-medium text-gray-900 dark:text-white">
                      {new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY' }).format(financialSummary.totalAmount)}
                    </span>
                  </div>
                  <div className="w-full bg-gray-200 dark:bg-slate-700 rounded-full h-1.5 mt-2">
                    <div 
                      className="bg-emerald-500 h-1.5 rounded-full" 
                      style={{ width: `${(financialSummary.paidAmount / financialSummary.totalAmount) * 100}%` }}
                    ></div>
                  </div>
                  <div className="flex justify-between text-[10px] mt-1 text-gray-500">
                    <span>Ödenen: {new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY' }).format(financialSummary.paidAmount)}</span>
                    <span>Kalan: {new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY' }).format(financialSummary.remainingAmount)}</span>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </ReactFlow>
      
      <FlowModals 
        showClearConfirm={showClearConfirm}
        onCloseClearConfirm={() => setShowClearConfirm(false)}
        onConfirmClear={confirmClear}
        showTemplateModal={showTemplateModal}
        onCloseTemplateModal={() => setShowTemplateModal(false)}
        templateName={templateName}
        onTemplateNameChange={setTemplateName}
        onSaveTemplate={handleSaveTemplate}
      />

      <RightDrawer agreementId={agreementId} />
    </div>
  );
}

export default function FlowCanvas({ workflowId, initialMode, onBack, onOpenSettings }: FlowProps) {
  return (
    <ReactFlowProvider>
      <Flow workflowId={workflowId} initialMode={initialMode} onBack={onBack} onOpenSettings={onOpenSettings} />
    </ReactFlowProvider>
  );
}
